---
title: "Homework 5"
author: "Matthew Parker"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

Read in the data and add missing
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```


Create a function that takes in a vector and does the following: 

* For numeric variables, it fills in missing values with the mean of non-missing values
* For character variables, it fills in missing values with `"virginica"`
```{r}
replace_miss = function(vec) {
  
  if (is.numeric(vec)) {
    if (length(vec) == 1) {
      stop("Missing cannot be replaced for numerical vector with length 1")
    } else {
    out = replace(vec, is.na(vec), round(mean(vec, na.rm = TRUE), 1))
    }
  } else if (is.character(vec)) {
    out = replace(vec, is.na(vec), "virginica")
  } else{
    stop("Missing cannot be replaced unless numerical or character vector")
  }
  
  out
  
}
```

Now apply map statement to apply `replace_miss` function to `iris_with_missing` df to replace missing values.
```{r}
output = map_dfr(iris_with_missing, replace_miss)
```

